### ISSUE TITLE
Indicate on whether we actually got realtime data

### ISSUE THREAD

**Issue by Kunsi** [Kunsi/package-hafas#7]

**Comment by sysvinit** [comment]
I've experimented with adding text to the display to indicate whether a service is on time or delayed based on real-time data, however it's not clear whether the delay information is actually useful or not. We've decided that a better approach would be to make the font faces for different parts of the display configurable. This would allow e.g. setting the departure time for services with real-time data to be displayed in italics or in a different colour.
