### ISSUE TITLE
Display stop names for stations with multiple merged stops

### ISSUE THREAD

**Issue by sysvinit** [Kunsi/package-hafas#8]
Currently we only display the departure (or arrival) stop for a given service when more than one stop is given in the config file. However, larger stations may have multiple services departing from different parts of the station (e.g. S-Bahn, U-Bahn, a bus stop outside the station building), each with their own stop ID's, which are merged into a single stop by the API. This could lead to some confusion if it's not clear which part of the station different services depart from, especially if platform numbers get re-used by different services.

We should change the logic for displaying multiple stop names to account for the different stop names returned by the API instead of what's returned in the configuration file.

(The motivating example for this issue is Bahnhof Berlin-Lichtenberg. The S-Bahn and U-Bahn both depart from platforms 1 and 2, but the U-Bahn platforms are in a different part of the station and have a different stop ID and name.)

**Comment by Kunsi** [comment]
fixed in 2f80154
